print("///////////////////////////TABLAS//////////////////////////")
num = int(input("inrese un numero para conocer su tabla de multiplicar:"))
print(f" x 1 = {num * 1 }")
print(f" x 2 = {num * 2 }")
print(f" x 3 = {num * 3 }")
print(f" x 4 = {num * 4 }")
print(f" x 5 = {num * 5 }")
print(f" x 6 = {num * 6 }")
print(f" x 7 = {num * 7 }")
print(f" x 8 = {num * 8 }")
print(f" x 9 = {num * 9 }")
print(f" x 10 = {num * 10 }")